// Posts.jsx
const posts = [
  {
    title: "USP",
    text: `Planground is professional software for architects to create floor plans. Its model-based geometry engine solves the core task of planning: arranging a defined set of rooms inside a given boundary.

It treats a plan as a geometric puzzle and computes layouts through iterative optimization. For any room program, it evaluates spatial configurations that meet required areas, relations, and the selected shape grammar.

The process works across four levels:

1. Text prompt — the user defines rooms, areas, constraints, and solver parameters.
2. Functional graph — Planground interprets the requirements and room relations.
3. Sketch zone — the engine produces a preliminary layout that the user can adjust by moving, resizing, adding, or removing rooms.
4. Finished plan — a complete plan generated by the selected solver, applying the chosen shape grammar and parameters.

Planground replaces manual wall drawing and the search for workable room configurations with a geometry solver that computes spatial solutions. Architects work directly with spaces while the engine resolves the geometry.`,
    image: "/usp-webp.webp",
    extraImages: [],
    showOrder: "image-first",
  },
  {
    title: "Examples",
    text: `Below are examples showing how an initial plan can be modified in sketch mode.

Rooms can be removed, resized, or repositioned, and the remaining rooms adapt automatically while preserving their relations.

The updated configuration is then rendered and interpreted by the user as a new finished plan.`,
    image: "/example1-webp.webp",
    extraImages: ["/example2-webp.webp", "/example3-webp.webp"],
    showOrder: "image-first",
  },
  {
    title: "Conferences and shows",
    text: "",
    image: "/misc1.webp",
    extraImages: ["/misc2.webp", "/misc3.webp"],
    showOrder: "text-first",
  },
];

export default posts;
